// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/akin.proto

package tencho

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Akin service

type AkinService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type akinService struct {
	c    client.Client
	name string
}

func NewAkinService(name string, c client.Client) AkinService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "tencho"
	}
	return &akinService{
		c:    c,
		name: name,
	}
}

func (c *akinService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Akin.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Akin service

type AkinHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterAkinHandler(s server.Server, hdlr AkinHandler, opts ...server.HandlerOption) error {
	type akin interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type Akin struct {
		akin
	}
	h := &akinHandler{hdlr}
	return s.Handle(s.NewHandler(&Akin{h}, opts...))
}

type akinHandler struct {
	AkinHandler
}

func (h *akinHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AkinHandler.Call(ctx, in, out)
}
