// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/demo.proto

package tosui

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tosui service

type TosuiService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type tosuiService struct {
	c    client.Client
	name string
}

func NewTosuiService(name string, c client.Client) TosuiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "tosui"
	}
	return &tosuiService{
		c:    c,
		name: name,
	}
}

func (c *tosuiService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Tosui.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tosui service

type TosuiHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterTosuiHandler(s server.Server, hdlr TosuiHandler, opts ...server.HandlerOption) error {
	type tosui interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type Tosui struct {
		tosui
	}
	h := &tosuiHandler{hdlr}
	return s.Handle(s.NewHandler(&Tosui{h}, opts...))
}

type tosuiHandler struct {
	TosuiHandler
}

func (h *tosuiHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.TosuiHandler.Hello(ctx, in, out)
}
