// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/demo.proto

package demo_tosu

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Tosu service

type TosuService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type tosuService struct {
	c    client.Client
	name string
}

func NewTosuService(name string, c client.Client) TosuService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "demo.tosu"
	}
	return &tosuService{
		c:    c,
		name: name,
	}
}

func (c *tosuService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Tosu.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tosu service

type TosuHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterTosuHandler(s server.Server, hdlr TosuHandler, opts ...server.HandlerOption) error {
	type tosu interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type Tosu struct {
		tosu
	}
	h := &tosuHandler{hdlr}
	return s.Handle(s.NewHandler(&Tosu{h}, opts...))
}

type tosuHandler struct {
	TosuHandler
}

func (h *tosuHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.TosuHandler.Hello(ctx, in, out)
}
