// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: k8s/proto/natsu.proto

package tencho

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Natsu service

type NatsuService interface {
	A(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type natsuService struct {
	c    client.Client
	name string
}

func NewNatsuService(name string, c client.Client) NatsuService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "tencho"
	}
	return &natsuService{
		c:    c,
		name: name,
	}
}

func (c *natsuService) A(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Natsu.A", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Natsu service

type NatsuHandler interface {
	A(context.Context, *Request, *Response) error
}

func RegisterNatsuHandler(s server.Server, hdlr NatsuHandler, opts ...server.HandlerOption) error {
	type natsu interface {
		A(ctx context.Context, in *Request, out *Response) error
	}
	type Natsu struct {
		natsu
	}
	h := &natsuHandler{hdlr}
	return s.Handle(s.NewHandler(&Natsu{h}, opts...))
}

type natsuHandler struct {
	NatsuHandler
}

func (h *natsuHandler) A(ctx context.Context, in *Request, out *Response) error {
	return h.NatsuHandler.A(ctx, in, out)
}
