// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: k8s/proto/natsu.proto

package tencho

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for NatSu service

type NatSuService interface {
	A(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type natSuService struct {
	c    client.Client
	name string
}

func NewNatSuService(name string, c client.Client) NatSuService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "tencho"
	}
	return &natSuService{
		c:    c,
		name: name,
	}
}

func (c *natSuService) A(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "NatSu.A", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NatSu service

type NatSuHandler interface {
	A(context.Context, *Request, *Response) error
}

func RegisterNatSuHandler(s server.Server, hdlr NatSuHandler, opts ...server.HandlerOption) error {
	type natSu interface {
		A(ctx context.Context, in *Request, out *Response) error
	}
	type NatSu struct {
		natSu
	}
	h := &natSuHandler{hdlr}
	return s.Handle(s.NewHandler(&NatSu{h}, opts...))
}

type natSuHandler struct {
	NatSuHandler
}

func (h *natSuHandler) A(ctx context.Context, in *Request, out *Response) error {
	return h.NatSuHandler.A(ctx, in, out)
}
